#!/bin/bash
# /etc/init.d/sorame_bot
# version 0.3.9 2012-08-13 (YYYY-MM-DD)

### BEGIN INIT INFO
# Provides:   sintyoku_bot
# Required-Start: $local_fs screen-cleanup
# Required-Stop:  $local_fs
# Should-Start:   $network
# Should-Stop:    $network
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: sintyoku_bot_core_system
# Description:    Service of sintyoku_bot
### END INIT INFO

#Settings
SERVICE='sintyoku.pl'
OPTIONS=''
BOTPATH='/home/fono/Github/sintyoku_bot'
INVOCATION="./sintyoku.pl"

sr_start() {
  if pgrep -f $SERVICE > /dev/null
  then
    echo "$SERVICE is already running!"
  else
    echo "Starting $SERVICE..."
    cd $BOTPATH
    screen -dmS sintyoku_bot $INVOCATION
    sleep 5
    if pgrep -f $SERVICE > /dev/null
    then
      echo "$SERVICE is now running."
    else
      echo "Error! Could not start $SERVICE!"
    fi
  fi
}

sr_stop() {
  if pgrep -f $SERVICE > /dev/null
  then
    echo "Stopping $SERVICE"
    killall $SERVICE
    sleep 5
  else
    echo "$SERVICE was not running."
  fi
  if pgrep -f $SERVICE > /dev/null
  then
    echo "Error! $SERVICE could not be stopped."
  else
    echo "$SERVICE is stopped."
  fi
}

#Start-Stop here
case "$1" in
  start)
    sr_start
    ;;
  stop)
    sr_stop
    ;;
  restart)
    sr_stop
    sr_start
    ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
  ;;
esac

exit 0
